spring:
  dynamic:
    master1:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
    master2:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
  jpa:
    show-sql: false
